// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMWXNnLvKYvwy8DPbTuPSbMA7MVg2LYYM',
    appId: '1:260431649114:web:1ea16c1f7cd57b43ca3b63',
    messagingSenderId: '260431649114',
    projectId: 'classwork6-db45b',
    authDomain: 'classwork6-db45b.firebaseapp.com',
    storageBucket: 'classwork6-db45b.appspot.com',
    measurementId: 'G-WR1EHL3N9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoaPblrNey4fi6Kos5dv2snVA_A1cmV-g',
    appId: '1:260431649114:android:f580c673fda7144fca3b63',
    messagingSenderId: '260431649114',
    projectId: 'classwork6-db45b',
    storageBucket: 'classwork6-db45b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY7jPguJmE9zJwS-14kiJbVjhmhQHOHcc',
    appId: '1:260431649114:ios:52fbc4532007dd52ca3b63',
    messagingSenderId: '260431649114',
    projectId: 'classwork6-db45b',
    storageBucket: 'classwork6-db45b.appspot.com',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY7jPguJmE9zJwS-14kiJbVjhmhQHOHcc',
    appId: '1:260431649114:ios:973a898935afac58ca3b63',
    messagingSenderId: '260431649114',
    projectId: 'classwork6-db45b',
    storageBucket: 'classwork6-db45b.appspot.com',
    iosBundleId: 'com.example.cw6.RunnerTests',
  );
}
